<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Zafaran Desktop</AssemblyName>
    <RootNamespace>SmartRestaurant.Desktop</RootNamespace>
    <ApplicationIcon></ApplicationIcon>
    <!-- allows building WPF on non-Windows CI -->
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.8" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\Fonts\**" />
  </ItemGroup>
</Project>
